vich_uploader:
    db_driver: orm

    mappings:
        delivrable_file:
           namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'fileSlug' }
           uri_prefix: /delivrables
           directory_namer: App\Upload\DelivrableDirectoryNamer
           upload_destination: '%kernel.project_dir%/public/delivrables'
        homework_file:
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'fileSlug' }
            uri_prefix: /homeworks
            upload_destination: '%kernel.project_dir%/public/homeworks'
            
           
